### PR TITLE
Ubuntu packaging fixes

### PR DESCRIPTION
**Pull request by Palakis**
- [x] Make the deb package require OBS v25.0.7 or higher
- [x] Remove the "Ubuntu dirty hack" from CMakeLists.txt and use standard GNU locations

### CODE REVIEW

**Comment by ShayBox** [comment]
`/usr/lib/obs-plugins` is the correct place to install obs plugins, this wasn't a hack, and this pr broke the plugin on non Ubuntu/(and maybe Debian) distros.  
`/usr/lib/x86_64-linux-gnu/obs-plugins` isn't recognized by stock obs, only by Ubuntus patched obs.

**Comment by kokigit** [comment]
confirming @ShayBox 
ubuntu 20.04
obs 25.0.8
obs-ndi 4.9.0

I have to copy obs-ndi.so to /usr/lib/obs-plugins in order to work
`sudo cp -a /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so /usr/lib/obs-plugins`

**Comment by maxdrash** [comment]
confirmed here Ubuntu 18.04 & 20.04

**Comment by led78** [comment]
Same here :

> confirming @ShayBox
> ubuntu 20.04
> obs 25.0.8
> obs-ndi 4.9.0
> 
> I have to copy obs-ndi.so to /usr/lib/obs-plugins in order to work
> `sudo cp -a /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so /usr/lib/obs-plugins`

**Comment by ShayBox** [comment]
For those unaware a patched build was released [here](https://github.com/Palakis/obs-ndi/releases/tag/4.9.1)

**Comment by maxdrash** [comment]
Sorry but when i try to build, cmake show it's the v 4.9.0 and still installing to 
-- Installing: /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so
-- Set runtime path of "/usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so" to ""
-- Installing: /usr/share/obs/obs-plugins/obs-ndi/locale/ca-ES.ini
-- Installing: /usr/share/obs/obs-plugins/obs-ndi/locale/en-US.ini
-- Installing: /usr/share/obs/obs-plugins/obs-ndi/locale/es-ES.ini
-- Installing: /usr/share/obs/obs-plugins/obs-ndi/locale/fr-FR.ini
-- Installing: /usr/share/obs/obs-plugins/obs-ndi/locale/ru-RU.ini
-- Installing: /usr/share/obs/obs-plugins/obs-ndi/locale/zh-CN.ini

**Pull request merged**
