### PR TITLE
Add customization of extra_ips parameter to find NDI sources

### PR DESCRIPTION
**Pull request by baracil**
The pull request add the possibility to customize 
the **'p_extra_ips'** parameters used for creating the
NDI find instance.

### CODE REVIEW

**Comment by LexusSpeed03** [comment]
Any luck on getting this added?

**Comment by jammerxd** [comment]
Can I get an upload from Baracil for windows binaries for this branch? I really need this feature.

**Comment by baracil** [comment]
You can get the Windows binaries from [NDI-OBS with ExtraIPs](http://femtoparsec.net/obs/obs-ndi-4.6.0-extra-ips-Windows.zip). This version add a field labeled "Extra IPs" in the NDI configuration (Tools > NDI Configuration). In this field, you provided the IP of the computer that is the NDI source (several values can be provided, they must be separated by a coma).

So in OBS, set the streaming interface (in Parameter->Advanced) then set the IP address of the NDI source in the "ExtraIps" field. Then when you add a NDI source in a scene, the NDI source PC should be available.

**Comment by Palakis** [comment]
@baracil Can you please fix the merge conflict?

Also, translations should not be handled in pull requests. They are made on Crowdin and then imported back to obs-ndi.

**Comment by baracil** [comment]
Hi @Palakis, I resolved the merge conflict. Sorry for the translations, I did not know you were using Crowdin.
Cheers

**Comment by ravenium** [comment]
Late to the party here, but would it be easier to have the plugin hook into NDI Access Manager, as it's intended for this purpose?

**Comment by MeDott29** [comment]
This is where the trail ends for me.  I still can't get NDI to use a dedicated IP address.  Am I missing something?

**Comment by ravenium** [comment]
> This is where the trail ends for me. I still can't get NDI to use a dedicated IP address. Am I missing something?

The NDI documentation is super foggy for this at times, but adding it will absolutely poll it.  Whether or not it responds depends on routing and firewall rules.  Have you tried firing up Wireshark and looking for the call-response?

**Comment by MeDott29** [comment]
@ravenium never used WireShark.  Now I feel guilty and ashamed for dropping out of my Networking 101 class.  I'm downloading it now and I'll sign up for Networking 101 tomorrow.

**Comment by fukeabigtime** [comment]
(am very new to github, so i may be out of place here, appologies if that is the case)
i just wanna point out the difference between ndi and ndihx:
https://support.newtek.com/hc/en-us/articles/360012318274-Linux-NDI-HX-Driver
Without the ndihx driver, obs-ndi would not see the hardware sender on my network.
Now with the driver properly installed and configured, obs-ndi does see it (but cannot process the audio/video , yet , unless I'm completely wrong)
reported the issue here (issue being libndihx.so is not loaded)
https://github.com/Palakis/obs-ndi/issues/558

again applogies is this msg is out of place.

**Comment by tt2468** [comment]
@baracil Sorry to have to ask again, but can you fix the merge conflict again?

**Comment by jrmann1999** [comment]
Since Covid is a thing, and I'm sure a lot of us are wanting to try to use OBS to do meetings.  NDI is useful when trying to stream from a home pc to a work PC, that then OBS virtual-camera can present to whatever meeting app.

The problem is for those of us with VPNs, the current implementation is returning TCP traffic down the default route (typically the VPN adapter) which is breaking things.  mDNS works, source show up on the client, just no video.  I've confirmed this with Wireshark, and also disabling the VPN.  Using ForceBindIP solves this, so it's definately something with OBS/NDI not fully binding the streams to the proper IP (not just the NIC).

Anything I can do to help debug/diagnose?  Is it still the NDI SDK that's holding up any feature related to binding to a specific IP?

**Comment by baracil** [comment]
Hello,

It has been a long time since I checked this repository (I'm not using the extra-ip option anymore). I even deleted my fork, so I'm not sure how to resolve the conflict from here.
It might be faster for me to fork from the current version en reimplement the modifications I did (that was not much if I recall).

**Comment by Palakis** [comment]
@baracil 
> 
> 
> Hello,
> 
> It has been a long time since I checked this repository (I'm not using the extra-ip option anymore). I even deleted my fork, so I'm not sure how to resolve the conflict from here.
> It might be faster for me to fork from the current version en reimplement the modifications I did (that was not much if I recall).

I'll see what I can do.

**Comment by tt2468** [comment]
Closing since this will be a feature of 5.0.0, which is a full rewrite.

**Comment by ogmkp** [comment]
It would be great if this feature can be reworked and added because of bad IGMP snooping or no possibility to configure NDI bridge.

**Pull request closed without merging**
